"""init

Revision ID: 815f88af8df6
Revises: 
Create Date: 2023-05-01 11:08:20.422923

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '815f88af8df6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('role_name', sa.String(length=256), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('role_name')
                    )
    op.create_table('User',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('mail', sa.String(length=256), nullable=False),
                    sa.Column('password', sa.String(length=256), nullable=False),
                    sa.Column('phone', sa.String(length=256), nullable=False),
                    sa.Column('company_name', sa.String(length=256), nullable=False),
                    sa.Column('mail_confirmed', sa.Boolean(), nullable=True),
                    sa.Column('date_reg', sa.TIMESTAMP(), nullable=False),
                    sa.Column('role_code', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['role_code'], ['Role.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('mail'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('phone')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Role')
    # ### end Alembic commands ###
