"""add refresh_token

Revision ID: b50f4259aff4
Revises: bd480b86dd3c
Create Date: 2023-05-02 13:07:36.306037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50f4259aff4'
down_revision = 'bd480b86dd3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'refresh_token')
    # ### end Alembic commands ###
