"""database v2

Revision ID: bd480b86dd3c
Revises: 5ddeabfabafa
Create Date: 2023-05-01 15:30:51.660550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd480b86dd3c'
down_revision = '5ddeabfabafa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
